let Selections = {
    select:{
        id:'select',
        name:'全体',
        display:'flex',
        process:function(){}
    },
    buyer:{
        id:'buyer',
        name:'売り屋',
        display:'block',
        serifs:{
            normal:[
                'おや、お客さんとは珍しいね<br>まあゆっくりしていきなよ',
                'ん？あーいらっしゃ〜い<br>え？キャラが違うって？<br>..このキャラを維持するのは難しくてね....'
            ],
        },
        process:function(){
            buyerOwnertext = arraySelect(Selections.buyer.serifs.normal);
            buyerOwnertextD.innerHTML = buyerOwnertext;
        }
    },
    mine:{
        id:'mine',
        name:'鉱山',
        display:'block',
        process:function(){}
    },
    shop:{
        id:'shop',
        name:'セイムマート',
        display:'block',
        process:function(){}
    },
    still:{
        id:'still',
        name:'まだ',
        display:'block',
        process:function(){}
    },
}